### ISSUE TITLE
About Microsoft Dolby Digital Atmos Pack

### ISSUE THREAD

**Issue by neptune84x** [SimonMacer/AnWave#20]
First of all, I would like to thank you for this wonderful work.
My question is that I want to extract only the Microsoft Dolby Digital Atmos Pack from anwave. 
Is this possible? Or can you offer the Microsoft Dolby Digital Atmos Pack as a separate package?

**Comment by SimonMacer** [comment]
I released Microsoft Dolby Digital Atmos Pack standalone installer. Now. You can download standalone installer to install.

【HOW-TO】Restore Microsoft Dolby Digital Decoder/Encoder MFT support in Windows 11, version 24H2:https://github.com/SimonMacer/AnWave/discussions/14

Microsoft Dolby Digital Atmos Pack version 10.0.22621.4169 standalone installer Download:
https://github.com/SimonMacer/AnWave/releases/tag/MSDDA-v10.0.22621.4169
