### ISSUE TITLE
WD

### ISSUE THREAD

**Issue by Klemci** [SimonMacer/AnWave#27]
Hello,

i'd like to know if an option or argument could be added to skip the Win Defender uninstall captcha code that has to be written !?

Also an option to skip WD uninstall to reset UAC ON !

And thanks

**Comment by SimonMacer** [comment]
> Hello,
> 
> i'd like to know if an option or argument could be added to skip the Win Defender uninstall captcha code that has to be written !?
> 
> Also an option to skip WD uninstall to reset UAC ON !
> 
> And thanks

Added in [AnWave 2024 version 4.132.25.12](https://github.com/SimonMacer/AnWave/releases/tag/AnWave-v4.132).

Edited: I re-release new version 4.132.25.12.

Now, you can enable Bypass Windows Defender removal captcha code dialog box & Remember User Account Control settings and restore. It's will skipping captcha code. And restore your UAC settings when processing completed.
