### ISSUE TITLE
Please info about 5.0.10.25 to 5.2.0.18 - LOG

### ISSUE THREAD

**Issue by Klemci** [SimonMacer/AnWave#28]
Hello,

i'm curious about the exact log between this two versions, that's because i used 5.0.10.25 on my 23H2 WIM to remove Win Defender and  want to be sure nothing changed in that part.

I had the _Skip Optionnal  Win Aps_ enabled btw, because i use ADK myself, i also i had already just slipstreamed last cumulative update and saved WIM just prior using AnWave on it ant the verry end, it perfectly worked tho :p 
Smartly enough i didn't manually  removed the "_Microsoft.SecHealthUI_1000.22621.1.0_x64__8wekyb3d8bbwe_" because i thinked AnWave would do it by itself in the process, and i've been right (lucky me).

So i'm concerned if AnWave update LOG concerns this part from 0.10.125 to 2.0.18 , if the WD WIM uninstall process had been updated/fixed in any way thanks.

The truth is that i'm mostly interested in the WD uninstall part of AnWave, it's exactly what i was after and when i read about it being possible to be done on WIM image i have been vrry pleased (as an ADK user), i like the other stuff available tho, great thanks ;)

**Comment by SimonMacer** [comment]
> Hello,
> 
> i'm curious about the exact log between this two versions, that's because i used 5.0.10.25 on my 23H2 WIM to remove Win Defender and want to be sure nothing changed in that part.
> 
> I had the _Skip Optionnal Win Aps_ enabled btw, because i use ADK myself, i also i had already just slipstreamed last cumulative update and saved WIM just prior using AnWave on it ant the verry end, it perfectly worked tho :p Smartly enough i didn't manually removed the "_Microsoft.SecHealthUI_1000.22621.1.0_x64__8wekyb3d8bbwe_" because i thinked AnWave would do it by itself in the process, and i've been right (lucky me).
> 
> So i'm concerned if AnWave update LOG concerns this part from 0.10.125 to 2.0.18 , if the WD WIM uninstall process had been updated/fixed in any way thanks.
> 
> The truth is that i'm mostly interested in the WD uninstall part of AnWave, it's exactly what i was after and when i read about it being possible to be done on WIM image i have been vrry pleased (as an ADK user), i like the other stuff available tho, great thanks ;)

Because I found some bugs in the driver decompression function, so I pulled down the previously version. The v5.2.0.18 only fix these problems.
- Fixed decompressing AMD/NVIDIA driver executable files may cause process lockup.
