### ISSUE TITLE
Microsoft Dolby Digital Atmos Pack does not work on windows 11 pro 24H2 os build: 26100.2033.

### ISSUE THREAD

**Issue by malcev1** [SimonMacer/AnWave#32]
I installed Microsoft Dolby Digital Atmos Pack v10.0.22621.4317, on windows 11 pro 24H2 os build: 26100.2033.
But it does not help me. 
Premiere CC does not see AC3 sound (It uses installed codecs in system).

**Comment by SimonMacer** [comment]
Premiere Pro CC 2023/2024/2025 only supports AC-3 decoding (AC-3 encoding requires SurCode license), and uses the system AC-3 decoding MFT. It's work fine.

I don't know which Premiere Pro CC version you are using.

**Comment by SimonMacer** [comment]
> I installed Microsoft Dolby Digital Atmos Pack v10.0.22621.4317, on windows 11 pro 24H2 os build: 26100.2033. But it does not help me. Premiere CC does not see AC3 sound (It uses installed codecs in system).

![ac33](https://github.com/user-attachments/assets/cdf6c9f4-2833-4f4a-a967-3e06960f5e0a)

It's work fine.

**Comment by malcev1** [comment]
I use Premiere Pro CC 2023.
Can you please try import  this ac3 file
https://drive.google.com/file/d/1F93Pu-GbwhSoFYOfvzXQQX2E1EjwJHQ6/view?usp=drive_link
I got an error, but in vlc it works fine.

**Comment by SimonMacer** [comment]
> I use Premiere Pro CC 2023. Can you please try import this ac3 file https://drive.google.com/file/d/1F93Pu-GbwhSoFYOfvzXQQX2E1EjwJHQ6/view?usp=drive_link I got an error, but in vlc it works fine.

Not related to AC-3 Codec. You have successfully installed Microsoft Dolby Digital Atmos Pack.

Premiere Pro CC does not support direct import of RAW AC-3 format. You need to mix *.ac3 to *.m2ts container.
Use: tsMuxer https://github.com/justdan96/tsMuxer
Download: https://www.videohelp.com/software/tsMuxeR

and It's work fine.
![ac34](https://github.com/user-attachments/assets/48b5eb1a-a14d-4d65-bd29-6f10519547ee)

**Comment by malcev1** [comment]
Ok. But  I cannot import vob file with ac3 audio.
On windows 10 I did it successfully.
Can you please try it
https://drive.google.com/file/d/1jrk_3m7ogXlbGixgqnxj2cyksDb2ZsHE/view?usp=drive_link

**Comment by SimonMacer** [comment]
> Ok. But I cannot import vob file with ac3 audio. On windows 10 I did it successfully. Can you please try it https://drive.google.com/file/d/1jrk_3m7ogXlbGixgqnxj2cyksDb2ZsHE/view?usp=drive_link

Rename "VTS_01_3.VOB" to "VTS_01_3.mpeg" and import this. PPro cannot recognize VOB format, just need change the file extension.

**Comment by malcev1** [comment]
I just tested - Vob file premiere understands correctly and imports with sound.
May be there were some problems with cached files.
Thank you!
